# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa9e583d6680f5be278f6c82e1780fb43f4d716dfc01c7e67a85585512fa38ea6d7f6f4a51ecfd1a6b30bc33799e98d3b83fed0a1f36e48fd50ec0dead305716

test:
  secret_key_base: b212b41c3c5b6652f15e56380bbe9fb878baf4b7ff8e88a0d018b0df73214a34fdc1960ee3165f9a3b99c44f5ca7c3292453eb2962d92ae93b18f98d8fd5958d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
